# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 Daniel Warhammar
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure OmniTools path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ omnitools_uid }}"
    group: "{{ omnitools_gid }}"
  with_items:
    - "{{ omnitools_base_path }}"

- name: Ensure OmniTools support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ omnitools_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ omnitools_uid }}"
    group: "{{ omnitools_gid }}"
  with_items:
    - env
    - labels
  register: omnitools_support_files_result

- name: Run if self-building of OmniTools container image is not enabled
  when: "not omnitools_container_image_self_build | bool"
  block:
    - name: Ensure OmniTools container image is pulled via community.docker.docker_image_pull
      when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
      community.docker.docker_image_pull:
        name: "{{ omnitools_container_image }}"
        pull: always
      register: omnitools_container_image_pull_result_ansible_module
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: omnitools_container_image_pull_result_ansible_module is not failed

    - name: Ensure OmniTools container image is pulled via ansible.builtin.command
      when: devture_systemd_docker_base_container_image_pull_method == 'command'
      ansible.builtin.command:
        cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ omnitools_container_image }}"
      register: omnitools_container_image_pull_result_command
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: omnitools_container_image_pull_result_command is not failed
      changed_when: "'Downloaded newer image' in omnitools_container_image_pull_result_command.stdout"

- name: Run if self-building of OmniTools container image is enabled
  when: "omnitools_container_image_self_build | bool"
  block:
    - name: Ensure OmniTools repository is present on self-build
      ansible.builtin.git:
        repo: "{{ omnitools_container_image_self_build_repo }}"
        version: "{{ omnitools_container_image_self_build_repo_version }}"
        dest: "{{ omnitools_container_image_self_build_src_files_path }}"
        force: "yes"
      register: omnitools_git_pull_results

    - name: Ensure OmniTools files for building container image installed
      ansible.builtin.template:
        src: "{{ role_path }}/templates/{{ item }}.j2"
        dest: "{{ omnitools_container_image_self_build_src_files_path }}/{{ item }}"
        mode: "0640"
        owner: "{{ omnitools_uid }}"
        group: "{{ omnitools_gid }}"
        force: true # Overwrite the default Dockerfile at https://raw.githubusercontent.com/iib0011/omni-tools/refs/heads/main/Dockerfile
      with_items:
        - .dockerignore
        - Dockerfile

    - name: Ensure OmniTools container image is built
      community.docker.docker_image_build:
        name: "{{ omnitools_container_image_self_build_name }}"
        dockerfile: Dockerfile
        path: "{{ omnitools_container_image_self_build_src_files_path }}"
        pull: true
        rebuild: "{{ 'always' if omnitools_git_pull_results.before != omnitools_git_pull_results.after | bool else 'never' }}"
      register: omnitools_container_image_build_result

- name: Ensure OmniTools container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ omnitools_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure OmniTools container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ omnitools_container_network }}
  register: network_creation_result
  changed_when: network_creation_result.rc == 0
  failed_when: network_creation_result.rc != 0 and 'already exists' not in network_creation_result.stderr

- name: Ensure OmniTools systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/omnitools.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ omnitools_identifier }}.service"
    mode: "0644"
  register: omnitools_systemd_service_result

- name: Determine whether OmniTools needs a restart
  ansible.builtin.set_fact:
    omnitools_restart_necessary: >-
      {{
        omnitools_support_files_result.changed | default(false)
        or omnitools_systemd_service_result.changed | default(false)
        or omnitools_container_image_pull_result_ansible_module.changed | default(false)
        or omnitools_container_image_pull_result_command.changed | default(false)
        or omnitools_container_image_build_result.changed | default(false)
      }}
