# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 Daniel Warhammar
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of OmniTools systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ omnitools_identifier }}.service"
  register: omnitools_service_stat

- name: Uninstall OmniTools systemd services and files
  when: omnitools_service_stat.stat.exists | bool
  block:
    - name: Ensure OmniTools systemd service is stopped
      ansible.builtin.service:
        name: "{{ omnitools_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure OmniTools systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ omnitools_identifier }}.service"
        state: absent

    - name: Ensure OmniTools container network does not exist
      when: omnitools_container_network_deletion_enabled
      block:
        - name: Ensure OmniTools container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ omnitools_container_network }}"
            state: absent
          register: omnitools_network_deletion_result

        - name: Ensure OmniTools container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ omnitools_container_network }}
          register: omnitools_network_deletion_result
          changed_when: omnitools_container_network in omnitools_network_deletion_result.stdout

    - name: Ensure OmniTools path does not exist
      ansible.builtin.file:
        path: "{{ omnitools_base_path }}"
        state: absent
